# Generated by Django 5.0.6 on 2024-07-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_funcionalidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionalidade',
            options={'verbose_name': 'Funcionario'},
        ),
    ]
